export const TANK_LIST_REQUEST = "TANK_LIST_REQUEST";
export const TANK_LIST_SUCCESS = "TANK_LIST_SUCCESS";
export const TANK_LIST_FAIL = "TANK_LIST_FAIL";

export const TANK_LIST_BY_USER_REQUEST = "TANK_LIST_BY_USER_REQUEST";
export const TANK_LIST_BY_USER_SUCCESS = "TANK_LIST_BY_USER_SUCCESS";
export const TANK_LIST_BY_USER_FAIL = "TANK_LIST_BY_USER_FAIL";

export const TANK_DETAILS_REQUEST = "TANK_DETAILS_REQUEST";
export const TANK_DETAILS_SUCCESS = "TANK_DETAILS_SUCCESS";
export const TANK_DETAILS_FAIL = "TANK_DETAILS_FAIL";

export const TANK_DELETE_REQUEST = "TANK_DELETE_REQUEST";
export const TANK_DELETE_SUCCESS = "TANK_DELETE_SUCCESS";
export const TANK_DELETE_FAIL = "TANK_DELETE_FAIL";

export const TANK_CREATE_REQUEST = "TANK_CREATE_REQUEST";
export const TANK_CREATE_SUCCESS = "TANK_CREATE_SUCCESS";
export const TANK_CREATE_FAIL = "TANK_CREATE_FAIL";
export const TANK_CREATE_RESET = "TANK_CREATE_RESET";

export const TANK_UPDATE_REQUEST = "TANK_UPDATE_REQUEST";
export const TANK_UPDATE_SUCCESS = "TANK_UPDATE_SUCCESS";
export const TANK_UPDATE_FAIL = "TANK_UPDATE_FAIL";
export const TANK_UPDATE_RESET = "TANK_UPDATE_RESET";
